### ISSUE TITLE
the results of the paper

### ISSUE THREAD

**Issue by Cherryreg** [XiaohanLei/IEVE#10]
Hello author, thank you for your answer to the previous issue. Through your suggestions, your method has been successfully repeated, and the results are better than those of the previous code.
The result of replicating episodes under 60 matches the 0.73 you mentioned in your previous issue.
However, I still have some questions. The result 0.684 or 0.702 in Table1 in the paper is the result of how many episodes.
Based on your modified code I'm reworking it and only getting 0.528 under 1000episodes Settings.
 
![image](https://github.com/user-attachments/assets/e87806f9-cd6d-43f9-ad8d-635c19b44634)

**Comment by XiaohanLei** [comment]
You can refer to this issue #6

**Comment by Cherryreg** [comment]
Thank you for your answer. I have two more questions:
Question 1: In Issue 6, you mentioned that the paper was tested on 100/200/500 eval episodes. I don't seem to find data on this in the paper.
Question 2: The result 0.684 or 0.702 in Table1 in the paper is the result of how many episodes.

**Comment by XiaohanLei** [comment]
For Q1 and Q2, the evaluation results in the paper is conducted under 100 episodes, which aims to align with [Semantic Exploration](https://github.com/devendrachaplot/Object-Goal-Navigation).
Some tips: the performance of IEVE highly depends on the local feature matching algorithm. In another work of mine: [GaussNav](https://github.com/XiaohanLei/GaussNav), we validate the impact of local feature matching algorithm on navigation performance. The [lightglue](https://github.com/cvg/LightGlue) of the last year version seems to produce far fewer matched keypoints. Thus I recommend try searching with different hyper-parameters in Switch module.
If you still have issues, feel free to contact me!

**Comment by XiaohanLei** [comment]
Close this issue because inactivity.
