### ISSUE TITLE
Visualization of final result and the possibility of interaction

### ISSUE THREAD

**Issue by Carton22** [XiaohanLei/IEVE#12]
@XiaohanLei 
Really fantastic work! 
I have been trying to follow README and **_test_** in the **_val_** dataset.
I can successfully running the `main.py`, and the current output is like the screenshot below
<img width="1090" alt="image" src="https://github.com/user-attachments/assets/969d38b4-86cd-4a32-a13f-6bb14e35fd3c" />
It seems that it would take several hours.
So based on this, I have 2 questions seeking for help
1. How to **_visualize_** the final results if finally I finish running `main.py`?
(I wanna have something like the `demo.gif` shown in README)
2. Is it possible to **_interact_** with the visualization or the final result? 
Like use left/right/up/down arrows to control the movement and navigation of the agent? 
Or other interaction ways to observe the final results more intuitively? Like for example see the results, give a prompt, etc

Thank you so much for your time and help!
Much appreciated!

**Comment by XiaohanLei** [comment]
For the first question, you can set `print_images` in arguments.py to 1. This command will save observations in tmp folder.
For the second question, we do not offer this function, but we recommend you to try the demo from [habitat-sim](https://github.com/facebookresearch/habitat-sim)

**Comment by Carton22** [comment]
<img width="1521" alt="image" src="https://github.com/user-attachments/assets/e00ebfcb-7493-4fcc-b640-b124fcb672fc" />
Thank you so much!
Problem solved.

One suggestion is it would be better if you could make it clear in **_README_** that
to print out the visualization you need to set up the print_images and visualization arguments

Much appreciated for all the help!
