### ISSUE TITLE
环境安装问题

### ISSUE THREAD

**Issue by Lotsoliu** [XiaohanLei/IEVE#2]
![屏幕截图 2024-07-05 160906](https://github.com/XiaohanLei/IEVE/assets/127647910/cdfe2fac-7822-42d6-b9c5-37fc8ff0ba76)
作者您好，配置环境的过程我发现需要maskdino这个包，但是并没有相关说明。希望您有时间可以看一下，谢谢！另外由于用到了swinv2，，torchvision版本必须在0.15以上，torch版本必须在2.0.0以上，其他朋友配置环境可以直接安装2.0.0以上的torch

**Comment by Lotsoliu** [comment]
![image](https://github.com/XiaohanLei/IEVE/assets/127647910/27457adf-b497-4206-9475-b22935e3a485)
https://github.com/IDEA-Research/MaskDINO

**Comment by XiaohanLei** [comment]
I'm sorry that I didn't carefully check the code before uploading it. The MaskDINO is unnecessary in the paper, therefore you can run the code without it. If you have any other questions, feel free to open issues!
Thanks!
