### ISSUE TITLE
model_parameter.pkl not found

### ISSUE THREAD

**Issue by Lotsoliu** [XiaohanLei/IEVE#3]
![Screenshot from 2024-07-06 19-33-16](https://github.com/XiaohanLei/IEVE/assets/127647910/161477a8-1d67-4b2e-9538-c8ff49ef7ad1)
Thank you for your awesome work!
I met a little difficulty in the reproduction as model_parameter.pkl has not been uploaded

**Comment by XiaohanLei** [comment]
I'm sorry that I foget to comment out unnecessary information in my original code. This file is unnecessary. You can run the code without it.

**Comment by yijieZengz** [comment]
您好，Lotsoliu，请问您是否成功复现了这篇工作呢，我想向你请教一些问题。（Hello, Lotsoliu, have you successfully reproduced this work? I would like to ask you some questions.）
