### ISSUE TITLE
Where is the code that specifies the target image for each epoch?

### ISSUE THREAD

**Issue by yijieZengz** [XiaohanLei/IEVE#7]
Hello author, I have contacted you through issue before, and thank you very much for your kind answer. Since I am new to this field, your answer is very important to me. Now I have a few more questions I'd like to ask you.

Question 1: Where is the code to set the target image of each epoch? (I tried to solve this problem by tracing the code by Debug, but I couldn't find it)

Question 2: How can I visualize the target image of each epoch or get the target image in RGB format?

If these problems can be solved, other problems that may depend on them will also be solved.

Thank you very much, and thank you again for your outstanding work and kind answers.

**Comment by XiaohanLei** [comment]
for the question 1,
https://github.com/XiaohanLei/IEVE/blob/32efac4d6352f8d3b3ff14376c042470814e1c63/envs/habitat/imagegoal_env.py#L324
for the question 2,
as long as you get the instance goal image (question 1), it is easy to visualize it
