### ISSUE TITLE
Where is docs/legend.png?

### ISSUE THREAD

**Issue by yijieZengz** [XiaohanLei/IEVE#9]
Hello author, when I was using the "--print_images  1 " to visualize, the following error occurred(As shown in the following picture). I found the following code in the “instance_exp.py” file, 

 if args.visualize or args.print_images:
            self.legend = cv2.imread('docs/legend.png')
            self.vis_image = None
            self.rgb_vis = None

but I can not find docs/legend.png.
 I inferred that it should be the reason for not finding  docs/legend.png, could you provide the file?
 Thank you for your kind answer and for your outstanding work！
<img width="819" alt="截屏2024-11-06 18 45 41" src="https://github.com/user-attachments/assets/55fdd154-941b-4d31-bd06-b5a93dedcdb9">

**Comment by XiaohanLei** [comment]
Thanks for pointing out this issue. Now we have updated the code.

**Comment by yijieZengz** [comment]
Thank you so much. I will try later.
